name: Pull Request Build
on:
    pull_request:
        branches: [ main ]

env:
    AWS_REGION: us-east-1

jobs:
    build-image:
        environment: default
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'temurin' # See 'Supported distributions' for available options
                    java-version: '17'
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                    aws-region: us-east-2
            -   name: Build and export
                run: |
                    #!/bin/bash
                    export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain demo --domain-owner 154987583424 --region us-east-1 --query authorizationToken --output text`
                    cat >settings.xml <<'EOF'
                       <settings>
                            <servers>
                                <server>
                                    <id>demo-demo_repo</id>
                                    <username>aws</username>
                                    <password>${env.CODEARTIFACT_AUTH_TOKEN}</password>
                                </server>
                            </servers>

                            <profiles>
                                <profile>
                                    <id>demo-demo_repo</id>
                                    <activation>
                                        <activeByDefault>true</activeByDefault>
                                    </activation>
                                    <repositories>
                                        <repository>
                                            <id>demo-demo_repo</id>
                                            <url>https://demo-154987583424.d.codeartifact.us-east-1.amazonaws.com/maven/demo_repo/</url>
                                        </repository>
                                    </repositories>
                                </profile>
                            </profiles>

                            <mirrors>
                                <mirror>
                                    <id>demo-demo_repo</id>
                                    <name>demo-demo_repo</name>
                                    <url>https://demo-154987583424.d.codeartifact.us-east-1.amazonaws.com/maven/demo_repo/</url>
                                    <mirrorOf>*</mirrorOf>
                                </mirror>
                            </mirrors>
                        </settings>
                    EOF
                    mvn clean install -s settings.xml
